# Generated by Django 5.1.5 on 2025-02-10 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[("FIC", "Fiction"), ("NON", "Non-Fiction")],
                        default="FIC",
                        max_length=3,
                    ),
                ),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_finished", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TBR", "To Be Read"),
                            ("RDG", "Reading"),
                            ("CMP", "Completed"),
                            ("DNF", "Did Not Finish"),
                        ],
                        default="TBR",
                        max_length=3,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Rating must be between 1 and 5"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "Rating must be between 1 and 5"
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_started", "-date_finished", "title"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="books_book_user_id_cf06b1_idx"
                    ),
                    models.Index(
                        fields=["user", "date_started"],
                        name="books_book_user_id_c17cc8_idx",
                    ),
                    models.Index(
                        fields=["user", "date_finished"],
                        name="books_book_user_id_5c4fed_idx",
                    ),
                ],
            },
        ),
    ]
