# Generated by Django 5.1.5 on 2025-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobhunt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="job_link",
            new_name="link",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="job_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="application",
            name="due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
