# Generated by Django 5.1.5 on 2025-01-28 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobhunt", "0004_alter_statuschange_options_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="role",
            field=models.CharField(
                choices=[
                    ("hiring_manager", "Hiring Manager"),
                    ("reference", "Reference"),
                    ("recruiter", "Recruiter"),
                    ("interviewer", "Interviewer"),
                    ("other", "Other"),
                ],
                default="hiring_manager",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("user", "email"),
                name="unique_user_email_if_exists",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone__isnull", False)),
                fields=("user", "phone"),
                name="unique_user_phone_if_exists",
            ),
        ),
    ]
