# Generated by Django 5.1.5 on 2025-01-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_friendship_rejected_by_alter_friendship_receiver_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("completions_10", "10 Completions"),
                            ("completions_50", "50 Completions"),
                            ("completions_100", "100 Completions"),
                            ("health_7_day", "7 Day Health Streak"),
                            ("health_30_day", "30 Day Health Streak"),
                            ("learning_7_day", "7 Day Learning Streak"),
                            ("learning_30_day", "30 Day Learning Streak"),
                            ("productivity_7_day", "7 Day Productivity Streak"),
                            ("productivity_30_day", "30 Day Productivity Streak"),
                            ("first_friend", "Made a Friend"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "badge_type")},
            },
        ),
    ]
