# Generated by Django 5.1.5 on 2025-01-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("completions_10", "10 Completions"),
                    ("completions_50", "50 Completions"),
                    ("completions_100", "100 Completions"),
                    ("health_7_day", "7 Day Health Streak"),
                    ("health_30_day", "30 Day Health Streak"),
                    ("learning_7_day", "7 Day Learning Streak"),
                    ("learning_30_day", "30 Day Learning Streak"),
                    ("productivity_7_day", "7 Day Productivity Streak"),
                    ("productivity_30_day", "30 Day Productivity Streak"),
                    ("first_friend", "Made a Friend"),
                    ("applications_5", "5 Applications Created"),
                    ("applied_5", "5 Applications Submitted"),
                    ("job_offered", "Job Offer Received"),
                    ("first_contact", "First Contact Added"),
                    ("wishlist_expired", "Wishlist Item Expired"),
                ],
                max_length=50,
            ),
        ),
    ]
