# Generated by Django 5.1.5 on 2025-01-19 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={},
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="awarded_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("completions_10", "10 Completions"),
                    ("completions_50", "50 Completions"),
                    ("completions_100", "100 Completions"),
                    ("health_7_day", "7 Day Health Streak"),
                    ("health_30_day", "30 Day Health Streak"),
                    ("learning_7_day", "7 Day Learning Streak"),
                    ("learning_30_day", "30 Day Learning Streak"),
                    ("productivity_7_day", "7 Day Productivity Streak"),
                    ("productivity_30_day", "30 Day Productivity Streak"),
                    ("first_friend", "Made a Friend"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
