# Generated by Django 5.1.5 on 2025-01-26 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_badge_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
